version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: sankhya
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
      TZ: UTC
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"   # opcional, só se quiser acessar de fora
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uapp", "-papp"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/sankhya?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      # SPRING_PROFILES_ACTIVE: prod
      TZ: UTC
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8080/api/v1/products?size=1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 25s

  frontend:
    build:
      context: ./frontend
      args:
        APP_NAME: frontend   # nome do projeto Angular (pasta em dist/)
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost/ >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

networks:
  default:
    name: sankhya-net

volumes:
  mysql_data:
